source 'https://rubygems.org'
source 'https://rails-assets.org' 

gem 'rails', '4.2.0'
gem 'mysql2', '~> 0.3.18'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'rails-assets-nvd3'
gem 'bootstrap-sass'
gem 'haml-rails'
gem 'react-rails', '~> 1.3.0'
gem 'react-router-rails', '~>0.13.3.1'
gem 'normalize-rails'

group :development do
  gem 'better_errors'
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
